version: 0.2

phases:
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -lock=false -input=false
      - terraform workspace select -or-create ${WORKSPACE}

      - terraform plan -var-file=${WORKSPACE_DIRECTORY}/${ACCOUNT_NAME}.tfvars 
  

  post_build:
    commands:
      - echo "plan complete"
