version: 0.2

phases:
  build:
    commands:   
      - cd "$CODEBUILD_SRC_DIR/$TERRAFORM_DIRECTORY"
      - terraform init -backend=false
      - terraform validate

  post_build:
    commands:
      - echo "validate complete"
